repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.6
    hooks:
      - id: uv-lock
        name: uv-lock-components
        args: ['--directory', 'services/components']
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              # Generated files
              .*\.kicad_.*$|
              .*\.(step|stp|STEP|STP)$|
              .*\.(wrl|WRL)$|
              .*\.dxf$|
              .*\.svg$|
              .*\.net$|
              .*/fp-lib-table$|
              .*\.(png|jpg|jpeg|gif|ico|gz|zip|7z|pdf)$
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
              # Generated files
              .*\.kicad_.*$|
              .*\.(step|stp|STEP|STP)$|
              .*\.(wrl|WRL)$|
              .*\.dxf$|
              .*\.svg$|
              .*\.net$|
              .*/fp-lib-table$|
              .*\.(png|jpg|jpeg|gif|ico|gz|zip|7z|pdf)$
          )$
