name: ato-build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad:main
        env:
          # FIXME: remove this once lazy-mifs are fully function
          FBRK_MAX_PATHS: 1e7
          FBRK_MAX_PATHS_NO_WEAK: 1e6
          FBRK_MAX_PATHS_NO_NEW_WEAK: 1e5

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
