
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad:pr-872
        env:
          FBRK_MAX_PATHS: 1e7
          FBRK_MAX_PATHS_NO_WEAK: 1e6
          FBRK_MAX_PATHS_NO_NEW_WEAK: 1e5

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
